retry datadog errors
omgnetwork/elixir-omg pull request #1774
Opened 2020-11-19 16:22 UTC by ayrat555

in https://github.com/omgnetwork/elixir-omg/commit/dcc2d3d05383531ececef79020c266d112fb1438 datadog metrics were introduced.

Datadog api is timing out during ci runs sometimes

2020-11-19 16:30 UTC, InoMurko requested changes

2020-11-19 16:30 UTC, InoMurko commented on priv/perf/apps/load_test/lib/service/datadog/api.ex
> +        end
why not provide a header function?
```
def fetch_events(start_time, end_time, environment, 0) do
##return error
```

just extract the query and you won't need to have a case inside a case

2020-11-19 17:09 UTC, InoMurko approved these changes

2020-11-20 03:19 UTC, achiurizo approved these changes

2020-11-20 03:24 UTC, boolafish approved these changes

2020-11-20 03:24 UTC, boolafish commented on priv/perf/apps/load_test/lib/service/datadog/api.ex
>          Logger.error("failed to resolve monitors #{inspect(error)}")
nitpick: I now is not part of this PR change. But might consider using warn level and add some words to indicate it is going to retry as it is still fighting to get out of the error.

2020-11-20 07:44 UTC, merged